version: '2'

services:
  frontend:
    build:
      context: ./assets
      dockerfile: Dockerfile-dev.mac
    image: nanocloud/frontend:dev.mac
    volumes:
      - ./assets:/front
      - static:/opt/dist
      - ./proxy/certificates:/opt/ssl/:ro
    ports:
      - 4200:4200
      - 49152:49152
    container_name: "frontend"

  proxy:
    image: nanocloud/proxy
    volumes:
      - ./proxy/nginx.dev.mac.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/certificates:/etc/nginx/ssl/:ro
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    container_name: "proxy"
    restart: always

  backend:
    build:
      context: ./
      dockerfile: Dockerfile-dev.mac
    image: nanocloud/backend-dev.mac
    volumes:
      - static:/opt/assets/dist
      - ./:/back
    env_file:
      - config.env
    environment:
      - DEV_MAC=true
    ports:
      - 5858:5858
      - 8081:8081
      - 1337:1337
    depends_on:
      - postgres
    container_name: "backend"

  postgres:
    image: postgres:9.5.3
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=nanocloud
    ports:
      - 5432:5432
    container_name: "postgres"

  storage:
    image: nanocloud/storage
    container_name: "storage"
    environment:
      - PLAZA_PORT=9090
    ports:
      - 9090:9090
    volumes:
      - plaza:/opt/plaza
    depends_on:
      - plaza

  storage-team:
    image: nanocloud/storage
    container_name: "storage-team"
    environment:
      - PLAZA_PORT=9091
    ports:
      - 9091:9091
    volumes:
      - plaza:/opt/plaza
    depends_on:
      - plaza

  plaza:
    build: ./plaza
    image: nanocloud/plaza
    environment:
      - GOOS=linux
      - GOARCH=amd64
    volumes:
      - plaza:/go/src/github.com/Nanocloud/nanocloud/plaza/

volumes:
  static:
    driver: local
  plaza:
    driver: local
