FROM nanocloud/backend
MAINTAINER OLivier Berthonneau <olivier.berthonneau@nanocloud.com>

RUN npm install nodemon node-inspector -g

EXPOSE 5858
EXPOSE 8081

RUN apt-get update && apt-get install -y lsyncd
RUN mkdir -p /opt/dist

COPY config/lsyncd_source /lsyncd_source
COPY config/start-dev-mac.sh /start-dev-mac.sh

CMD bash /start-dev-mac.sh
