FROM nanocloud/backend
MAINTAINER Olivier Berthonneau <olivier.berthonneau@nanocloud.com>

RUN npm install nodemon node-inspector -g

EXPOSE 5858
EXPOSE 8081

CMD npm install && (node-inspector --web-port=8081 &) && nodemon --exec 'node --debug' app.js
